### ISSUE TITLE
Certificate is bound localhost

### ISSUE THREAD

**Issue by redhead** [qa/course-sys-int-systems-exam#4]
.. but we need to access it throught different IP (because docker)

```
javax.net.ssl.SSLException: hostname in certificate didn't match: <192.168.59.103> != <localhost>
```

**Comment by redhead** [comment]
I found (a workaround?) I can use `x509HostnameVerifier` option on http4 component to bypass the check. Is that OK or I need to do something else?

**Comment by redhead** [comment]
I found (a workaround?) I can use `x509HostnameVerifier` option on http4 component to bypass the check. Is that OK or I need to do something else?

**Comment by jpechane** [comment]
Great, could you please add it as a comment to project page? We created certificate intentionally to use localhost as we supposed that it will be bound to the localhost network interface. But if somebody does it differently then this is good solution/workaround.
